name: Native (wasm-customized marian)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-macos:
    name: MacOS CPU-only
    runs-on: macos-10.15

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake cmake \
          -DCOMPILE_CUDA=off \
          -DUSE_DOXYGEN=off \
          -DCOMPILE_EXAMPLES=off \
          -DCOMPILE_SERVER=off \
          -DCOMPILE_TESTS=off \
          -DUSE_FBGEMM=off \
          -DUSE_SENTENCEPIECE=on \
          -DUSE_STATIC_LIBS=on \
          -DUSE_MKL=off \
          -DUSE_WASM_COMPATIBLE_SOURCE=on ../

    - name: Compile
      working-directory: build
      run: make -j2

    - name: Print versions
      working-directory: build
      run: |
        ./marian-decoder --version

